export const EFFECT = {
  acidic: 'extrabees.effect.acid',
  birthday: 'extrabees.effect.birthday',
  darkness: 'extrabees.effect.blindness',
  ripening: 'extrabees.effect.bonemeal_fruit',
  mushroom: 'extrabees.effect.bonemeal_mushroom',
  growth: 'extrabees.effect.bonemeal_sapling',
  confusion: 'extrabees.effect.confusion',
  ectoplasm: 'extrabees.effect.ectoplasm',
  festival: 'extrabees.effect.festival',
  fireworks: 'extrabees.effect.fireworks',
  nourishment: 'extrabees.effect.food',
  gravity: 'extrabees.effect.gravity',
  hunger: 'extrabees.effect.hunger',
  lightning: 'extrabees.effect.lightning',
  meteor: 'extrabees.effect.meteor',
  power: 'extrabees.effect.power',
  unstable: 'extrabees.effect.radioactive',
  slowness: 'extrabees.effect.slow',
  creepers: 'extrabees.effect.spawn_creeper',
  skeletons: 'extrabees.effect.spawn_skeleton',
  zombies: 'extrabees.effect.spawn_zombie',
  teleport: 'extrabees.effect.teleport',
  antigravity: 'extrabees.effect.thief',
  water: 'extrabees.effect.water',
  wither: 'extrabees.effect.wither',
  aggressive: 'forestry.effectAggressive',
  beatific: 'forestry.effectBeatific',
  creeper: 'forestry.effectCreeper',
  drunkard: 'forestry.effectDrunkard',
  explorer: 'forestry.effectExploration',
  fertile: 'forestry.effectFertile',
  festive: 'forestry.effectFestiveEaster',
  freezing: 'forestry.effectGlacial',
  heroic: 'forestry.effectHeroic',
  flammable: 'forestry.effectIgnition',
  poison: 'forestry.effectMiasmic',
  ends: 'forestry.effectMisanthrope',
  mycophilic: 'forestry.effectMycophilic',
  none: 'forestry.effectNone',
  radioactive: 'forestry.effectRadioactive',
  reanimation: 'forestry.effectReanimation',
  repulsion: 'forestry.effectRepulsion',
  resurrection: 'forestry.effectResurrection',
  snow: 'forestry.effectSnowing',
} as const;

export const FLOWER = {
  books: 'extrabees.flower.book',
  deadBush: 'extrabees.flower.dead',
  fruit: 'extrabees.flower.fruit',
  leaves: 'extrabees.flower.leaves',
  mystical: 'extrabees.flower.mystical',
  redstone: 'extrabees.flower.redstone',
  rocks: 'extrabees.flower.rock',
  saplings: 'extrabees.flower.sapling',
  reeds: 'extrabees.flower.sugar',
  lilyPad: 'extrabees.flower.water',
  wood: 'extrabees.flower.wood',
  cacti: 'forestry.flowersCacti',
  end: 'forestry.flowersEnd',
  gourds: 'forestry.flowersGourd',
  jungle: 'forestry.flowersJungle',
  mushroom: 'forestry.flowersMushrooms',
  nether: 'forestry.flowersNether',
  snow: 'forestry.flowersSnow',
  flowers: 'forestry.flowersVanilla',
  wheat: 'forestry.flowersWheat',
} as const;

export const FERTILITY = {
  high: 'forestry.fertilityHigh',
  low: 'forestry.fertilityLow',
  maximum: 'forestry.fertilityMaximum',
  normal: 'forestry.fertilityNormal',
} as const;

export const FLOWERING = {
  average: 'forestry.floweringAverage',
  fast: 'forestry.floweringFast',
  faster: 'forestry.floweringFaster',
  fastest: 'forestry.floweringFastest',
  maximum: 'forestry.floweringMaximum',
  slow: 'forestry.floweringSlow',
  slower: 'forestry.floweringSlower',
  slowest: 'forestry.floweringSlowest',
} as const;

export const LIFESPAN = {
  elongated: 'forestry.lifespanElongated',
  long: 'forestry.lifespanLong',
  longer: 'forestry.lifespanLonger',
  longest: 'forestry.lifespanLongest',
  normal: 'forestry.lifespanNormal',
  short: 'forestry.lifespanShort',
  shortened: 'forestry.lifespanShortened',
  shorter: 'forestry.lifespanShorter',
  shortest: 'forestry.lifespanShortest',
} as const;

export const SPEED = {
  fast: 'forestry.speedFast',
  faster: 'forestry.speedFaster',
  fastest: 'forestry.speedFastest',
  normal: 'forestry.speedNormal',
  slow: 'forestry.speedSlow',
  slower: 'forestry.speedSlower',
  slowest: 'forestry.speedSlowest',
} as const;

export const TERRITORY = {
  average: 'forestry.territoryAverage',
  large: 'forestry.territoryLarge',
  larger: 'forestry.territoryLarger',
  largest: 'forestry.territoryLargest'
} as const;

export const TOLERANCE = {
  both1: 'forestry.toleranceBoth1',
  both2: 'forestry.toleranceBoth2',
  both3: 'forestry.toleranceBoth3',
  both4: 'forestry.toleranceBoth4',
  both5: 'forestry.toleranceBoth5',
  down1: 'forestry.toleranceDown1',
  down2: 'forestry.toleranceDown2',
  down3: 'forestry.toleranceDown3',
  down4: 'forestry.toleranceDown4',
  down5: 'forestry.toleranceDown5',
  none: 'forestry.toleranceNon',
  up1: 'forestry.toleranceUp1',
  up2: 'forestry.toleranceUp2',
  up3: 'forestry.toleranceUp3',
  up4: 'forestry.toleranceUp4',
  up5: 'forestry.toleranceUp5',
} as const;
