const BIOME = {
  beach: 'Beach',
  birchForest: 'Birch Forest',
  birchForestHills: 'Birch Forest Hills',
  birchForestHillsM: 'Birch Forest Hills M',
  birchForestM: 'Birch Forest M',
  coldBeach: 'Cold Beach',
  coldTaiga: 'Cold Taiga',
  coldTaigaHills: 'Cold Taiga Hills',
  coldTaigaM: 'Cold Taiga M',
  deepOcean: 'Deep Ocean',
  desert: 'Desert',
  desertM: 'Desert M',
  desertHills: 'DesertHills',
  extremeHills: 'Extreme Hills',
  extremeHillsEdge: 'Extreme Hills Edge',
  extremeHillsM: 'Extreme Hills M',
  extremeHillsPlus: 'Extreme Hills+',
  extremeHillsPlusM: 'Extreme Hills+ M',
  flowerForest: 'Flower Forest',
  forest: 'Forest',
  forestHills: 'ForestHills',
  frozenOcean: 'FrozenOcean',
  frozenRiver: 'FrozenRiver',
  nether: 'Hell',
  iceMountains: 'Ice Mountains',
  icePlains: 'Ice Plains',
  icePlainsSpikes: 'Ice Plains Spikes',
  jungle: 'Jungle',
  jungleM: 'Jungle M'
} as const;

export default BIOME;
