const BIOME = {
  beach: 'Beach',
  birchForest: 'BirchForest',
  birchForestHills: 'BirchForestHills',
  birchForestHillsM: 'BirchForestHillsM',
  birchForestM: 'BirchForestM',
  coldBeach: 'ColdBeach',
  coldTaiga: 'ColdTaiga',
  coldTaigaHills: 'ColdTaigaHills',
  coldTaigaM: 'ColdTaigaM',
  deepOcean: 'DeepOcean',
  desert: 'Desert',
  desertM: 'DesertM',
  desertHills: 'DesertHills',
  extremeHills: 'ExtremeHills',
  extremeHillsEdge: 'ExtremeHillsEdge',
  extremeHillsM: 'ExtremeHillsM',
  extremeHillsPlus: 'ExtremeHills+',
  extremeHillsPlusM: 'ExtremeHills+M',
  flowerForest: 'FlowerForest',
  forest: 'Forest',
  forestHills: 'ForestHills',
  frozenOcean: 'FrozenOcean',
  frozenRiver: 'FrozenRiver',
  nether: 'Hell',
  iceMountains: 'IceMountains',
  icePlains: 'IcePlains',
  icePlainsSpikes: 'IcePlainsSpikes',
  jungle: 'Jungle',
  jungleM: 'JungleM'
} as const;

export default BIOME;
