const BRANCH = {
  honey: 'bees.honey',
  noble: 'bees.noble',
  industrious: 'bees.industrious',
  heroic: 'bees.heroic',
  infernal: 'bees.infernal',
  austere: 'bees.austere',
  tropical: 'bees.tropical',
  end: 'bees.end',
  frozen: 'bees.frozen',
  vengeful: 'bees.vengeful',
  festive: 'bees.festive',
  agrarian: 'bees.agrarian',
  boggy: 'bees.boggy',
  monastic: 'bees.monastic',
  barren: 'bees.barren',
  hostile: 'bees.hostile',
  rocky: 'bees.rocky',
  rusty: 'bees.metallic',
  metallic: 'bees.metallic2',
  alloy: 'bees.alloy',
  precious: 'bees.precious',
  mineral: 'bees.mineral',
  gemstone: 'bees.gemstone',
  nuclear: 'bees.nuclear',
  historic: 'bees.historic',
  fossilized: 'bees.fossilized',
  refined: 'bees.refined',
  aquatic: 'bees.aquatic',
  saccharine: 'bees.saccharine',
  classical: 'bees.classical',
  volcanic: 'bees.volcanic',
  virulent: 'bees.virulent',
  viscous: 'bees.viscous',
  caustic: 'bees.caustic',
  energetic: 'bees.energetic',
  farming: 'bees.farming',
  shadow: 'bees.shadow',
  primary: 'bees.primary',
  secondary: 'bees.secondary',
  tertiary: 'bees.tertiary',
  ftb: 'bees.ftb',
  quantum: 'bees.quantum',
  botania: 'bees.botania',
  patreon: 'gendustry.patreon',
} as const;

export default BRANCH;
