export const BRANCHES = {
  honey: 'genus.bees.honey',
  noble: 'genus.bees.noble',
  industrious: 'genus.bees.industrious',
  heroic: 'genus.bees.heroic',
  infernal: 'genus.bees.infernal',
  austere: 'genus.bees.austere',
  tropical: 'genus.bees.tropical',
  end: 'genus.bees.end',
  frozen: 'genus.bees.frozen',
  vengeful: 'genus.bees.vengeful',
  festive: 'genus.bees.festive',
  agrarian: 'genus.bees.agrarian',
  boggy: 'genus.bees.boggy',
  monastic: 'genus.bees.monastic',
  barren: 'genus.bees.barren',
  hostile: 'genus.bees.hostile',
  rocky: 'genus.bees.rocky',
  metallic: 'genus.bees.metallic',
  metallic2: 'genus.bees.metallic2',
  alloy: 'genus.bees.alloy',
  precious: 'genus.bees.precious',
  mineral: 'genus.bees.mineral',
  gemstone: 'genus.bees.gemstone',
  nuclear: 'genus.bees.nuclear',
  historic: 'genus.bees.historic',
  fossilized: 'genus.bees.fossilized',
  refined: 'genus.bees.refined',
  aquatic: 'genus.bees.aquatic',
  saccharine: 'genus.bees.saccharine',
  classical: 'genus.bees.classical',
  volcanic: 'genus.bees.volcanic',
  virulent: 'genus.bees.virulent',
  viscous: 'genus.bees.viscous',
  caustic: 'genus.bees.caustic',
  energetic: 'genus.bees.energetic',
  farming: 'genus.bees.farming',
  shadow: 'genus.bees.shadow',
  primary: 'genus.bees.primary',
  secondary: 'genus.bees.secondary',
  tertiary: 'genus.bees.tertiary',
  ftb: 'genus.bees.ftb',
  quantum: 'genus.bees.quantum',
  botania: 'genus.bees.botania',
  patreon: 'genus.gendustry.patreon',
} as const;

export default BRANCHES;
