const LIQUID = {
  acid: 'acid',
  aerotheum: 'aerotheum',
  bioEthanol: 'bioethanol',
  biofuel: 'biofuel',
  biomass: 'biomass',
  chocolateMilk: 'chocolatemilk',
  coal: 'coal',
  cryotheum: 'cryotheum',
  cyanite: 'cyanite',
  ender: 'ender',
  glass: 'glass',
  glowstone: 'glowstone',
  honey: 'honey',
  juice: 'juice',
  lava: 'lava',
  liquidDNA: 'liquiddna',
  liquidNitrogen: 'liquidnitrogen',
  mead: 'mead',
  meat: 'meat',
  milk: 'milk',
  mobEssence: 'mobessence',
  mushroomSoup: 'mushroomsoup',
  mutagen: 'mutagen',
  petrotheum: 'petrotheum',
  pinkSlime: 'pinkslime',
  poison: 'poison',
  protein: 'protein',
  pyrotheum: 'pyrotheum',
  redstone: 'redstone',
  seedOil: 'seedoil',
  sewage: 'sewage',
  shortMead: 'short',
  sludge: 'sludge',
  steam: 'steam',
  water: 'water',
  witchWater: 'witchwater',
  yellorium: 'yellorium',
} as const;

export default LIQUID;
